name: Build

on:
  schedule:
    - cron: 00 17 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - "inspiron7586"
    steps:
      - run: sudo mkdir /nix
      - uses: easimon/maximize-build-space@v6
        with:
          root-reserve-mb: 2048
          build-mount-path: /nix
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"
          extra_nix_config: "experimental-features = nix-command"
      - uses: cachix/cachix-action@v12
        with:
          name: hacker1024
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: NIX_PATH="$NIX_PATH:nixos-config=$GITHUB_WORKSPACE/${{ matrix.device }}/configuration.nix" nix-shell -p 'nix-build-uncached' --run "nix-build-uncached --no-out-link '<nixpkgs/nixos>' -A config.system.build.toplevel"
